### ISSUE TITLE
SuperX3 digital raw position vs energy plots not filling correctly

### ISSUE THREAD

**Issue by dwalter16** [ksmith0/goddess_daq#2]
These histograms are filled around line 451 in GoddessData.cxx. If you only use the frontRawEn[near] and fronRawEn[far] parameters to fill the histograms (sx3PosRaw_EnRaw and sx3nearfar) then they seems to be working fine for all of the analog detectors. The digital histograms are being filled with weird values and have significantly less counts.

**Comment by mhall12** [comment]
I changed the code around a little in GoddessData.cxx, and found that if I change the iterator to go from 1-8 instead of 0-7 for the contacts, some of the digital near far histograms actually fill with data and look like they're supposed to. I still don't think that this is correct, but it's the only way I have found to get anything into those histograms.

**Comment by dwalter16** [comment]
This stems from the digital channels starting at 1 instead of 0. We outputted each digitizer channel and corresponding detector channel and which detector it corresponds to; this was done in the SetRawValue function in GoddessConfig.cxx. In QQQ5_UA, channel 0 is never read out, and channel 32 is actually channel 0 of QQQ5_UB. Digitizer channel 32 should be the last strip of QQQ5_UA.

**Comment by ksmith0** [comment]
This should be corrected with a correction of goddess.config.

**Comment by ksmith0** [comment]
This is still an open issue as the current committed version of goddess.config in the master branch has the digital channels improperly mapped. If the debug branch is stable we should merge it back into master and mark this issue as closed.

**Comment by dwalter16** [comment]
The changes in the Debug branch have been merged with the master branch. I am gonna go ahead and close this issue.

**Comment by ksmith0** [comment]
Corrected in commit fe6b3ff9d944d511f688912663bb32d341ac4d36
