### ISSUE TITLE
Analog data missing in most recent runs

### ISSUE THREAD

**Issue by dwalter16** [ksmith0/goddess_daq#5]
The newest files that were copied and sorted do not have any analog data. The ldf files have a lot of reasonable data that looks fine on the ornl daq computer, but when it is copied and sorted on the dgs computers, the analog data "dissapears" (i.e. the agod_en plot and analog detector plots do not fill).
I think this is related to the inverted time events showing up in the ldf buffer. The weird events appear to crash the ornl daq scan and then needs to be restarted. An example of these weird events is a channel that has fired that is well out of the channel range of the adc, such as channel 1004.
This all started after the ldf buffer was changed to add in 2 more time stamps (internal vme time) with ID's=1003, 1004 which come before the myriad time stamps(1000,1001,1002) in the buffer.
This may have to do with the ldfconverter that needs to be updated to handle this new buffer format.

p.s. I have copied run284.ldf and the merged file to the tichy computer (Desktop) to look over

**Comment by ksmith0** [comment]
You should have tagged me in this so I would have seen it sooner. I'll start looking at it right away.

Did the myriad malformed rate increase when these were added? Or did the live time go down? We have to be careful what we put into the VME acq as it is very sensitive to speed.

**Comment by ksmith0** [comment]
The data sorting issue should have been corrected in commit 5a9867cb92e4e. 

This does not resolve the high malformed data rate which is very concerning. I'm closing this issue as the malformed rate does not come directly from this project, but this should be addressed immediately.

**Comment by trbaugher** [comment]
I've located where the myriad events started going bad. Maybe I send
you data from either side of the change and you can take a look?

**Comment by ksmith0** [comment]
Yes lets do this, and I need to know what changed at those points.

**Comment by ksmith0** [comment]
Below is a plot of the number of ADCs per analog trigger from run 284. Clearly this is abnormal, I believe there is a multiple trigger issue or a vmeacq issue.
![mult](https://cloud.githubusercontent.com/assets/7395803/9585349/57ed4384-4fe4-11e5-8794-4104b152ad37.png)

**Comment by ksmith0** [comment]
Below is a plot of the multiplicity of each DAQ channel in a given event. It seems to be an issue from a number of ADC modules.

![multbychannel](https://cloud.githubusercontent.com/assets/7395803/9588139/93115ba2-4ff4-11e5-8374-2d42b9fa9997.png)

**Comment by ksmith0** [comment]
A comparison of parameters per trigger for three runs.
![mult](https://cloud.githubusercontent.com/assets/7395803/9588519/dd932eb0-4ff6-11e5-8127-ba359b5dbf2e.png)

**Comment by ksmith0** [comment]
Added warning messages about multiple hits in a single parameter in hribfConvert in commit 88d8977e3b1da09f61b92480c1a7894f8939b6b6. This warning message should be seen very infrequently if everything is working as expected.

**Comment by ksmith0** [comment]
Jeff Blackmon discovered the veto was disconnected.
